# localhost 
GET http://localhost:8080/contacts HTTP/1.1

### Get contact by Id
GET http://localhost:8080/contacts/65ac19a9f3ba0aa07938be2a HTTP/1.1

###
GET http://localhost:8080/contacts/65ac19f8f3ba0aa07938be2c HTTP/1.1

###
GET http://localhost:8080/contacts/65ac1a1bf3ba0aa07938be2d HTTP/1.1

### create contact
POST http://localhost:8080/contacts HTTP/1.1
content-Type: application/json

{  
  "firstName": "Bonnette",
  "lastName": "Romero",
  "email": "rom20014@byui.edu",
  "favoriteColor": "Green",
  "birthday": "June 5, 1975"
  }

### Update contact
PUT http://localhost:8080/contacts/65b142ee4fa0a54924567aa7 HTTP/1.1
content-Type: application/json

{
 "firstName": "Bonnette",
  "lastName": "Lemmons",
  "email": "romerobonnette@byui.edu",
  "favoriteColor": "Green",
  "birthday": "June 5, 1975"

}


### DELETE contact
DELETE http://localhost:8080/contacts/65b142ee4fa0a54924567aa7 HTTP/1.1




### Render
GET http://blromero-cse341-week2.onrender.com/contacts HTTP/1.1

###
GET https://blromero-cse341-week2.onrender.com/contacts/65ac19a9f3ba0aa07938be2a HTTP/1.1

###
GET https://blromero-cse341-week2.onrender.com/contacts/65ac19f8f3ba0aa07938be2c HTTP/1.1
###
Get https://blromero-cse341-week2.onrender.com/contacts/65ac1a1bf3ba0aa07938be2d HTTP/1.1

###
POST https://blromero-cse341-week2.onrender.com/contacts HTTP/1.1
Content-Type: application/json

  {  
    "firstName": "Bonnette",
    "lastName": "Lemmons",
    "email": "rom20014@byui.edu",
    "favoriteColor": "Yellow",
    "birthday": "June 5, 1975"
  }


###
GET https://blromero-cse341-week2.onrender.com/contacts/65b187fde4b439c6a89f6e68 HTTP/1.1


###
PUT https://blromero-cse341-week2.onrender.com/contacts/65b187fde4b439c6a89f6e68 HTTP/1.1
Content-Type: application/json

{  
  "firstName": "Bonnette",
  "lastName": "Romero",
  "email": "romerobonnette@byui.edu",
  "favoriteColor": "Green",
  "birthday": "June 5, 1975"
  }

###
DELETE https://blromero-cse341-week2.onrender.com/contacts/65b1869327229c914a7c725c HTTP/1.1


